fix: Add parallelize() call after data_dependent_initialize
Fixes AttributeError: 'ResnetGenerator' object has no attribute 'module'
when saving networks. The networks need to be wrapped in DataParallel
before save_networks() is called.